name: Build Quantum Translator

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller deep-translator requests
          pip install pyperclip 

      - name: Build Executable
        run: pyinstaller --onefile --console --name Translator --collect-all deep_translator translator.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: PythonTranslator
          path: dist/Translator.exe
          if-no-files-found: error
          retention-days: 100
